;
; Alex vs Bus (MD port)
; Copyright (C) 2021-2026 M374LX
;
; This program is free software: you can redistribute it and/or modify
; it under the terms of the GNU General Public License as published by
; the Free Software Foundation, either version 3 of the License, or
; (at your option) any later version.
;
; This program is distributed in the hope that it will be useful,
; but WITHOUT ANY WARRANTY; without even the implied warranty of
; MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
; GNU General Public License for more details.
;
; You should have received a copy of the GNU General Public License
; along with this program.  If not, see <https://www.gnu.org/licenses/>.
;

;
; File:
; constants.asm
;
; Description:
; Definition of constants
;

; ------------------------------------------------------------------------------

; Sega Genesis screen size
SCREEN_W:   equ 320
SCREEN_H:   equ 224

; VDP port addresses
VDP_CTRL:   equ $C00004
VDP_DATA:   equ $C00000

; SRAM
SRAM_LOCK:  equ $A130F1
SRAM_START: equ $200000

; Sprites
SPR_INITIAL: equ $01F0
SPR_NULL: equ SPR_INITIAL+$0000
SPR_PLAYER_HEAD: equ SPR_INITIAL+$0001
SPR_PLAYER_TORSO_1: equ SPR_INITIAL+$0002
SPR_PLAYER_TORSO_2: equ SPR_INITIAL+$0008
SPR_PLAYER_TORSO_3: equ SPR_INITIAL+$000E
SPR_PLAYER_TORSO_4: equ SPR_INITIAL+$0014
SPR_PLAYER_TORSO_5: equ SPR_INITIAL+$001A
SPR_PLAYER_LEGS_1: equ SPR_INITIAL+$0020
SPR_PLAYER_LEGS_2: equ SPR_INITIAL+$0028
SPR_PLAYER_LEGS_3: equ SPR_INITIAL+$0038
SPR_PLAYER_LEGS_4: equ SPR_INITIAL+$0044
SPR_PLAYER_LEGS_5: equ SPR_INITIAL+$004C
SPR_PLAYER_LEGS_6: equ SPR_INITIAL+$005C
SPR_PLAYER_LEGS_7: equ SPR_INITIAL+$0068
SPR_PLAYER_LEGS_8: equ SPR_INITIAL+$0070
SPR_PLAYER_LEGS_9: equ SPR_INITIAL+$0078
SPR_PLAYER_LEGS_10: equ SPR_INITIAL+$0080
SPR_PLAYER_LEGS_11: equ SPR_INITIAL+$0088
SPR_PLAYER_LEGS_12: equ SPR_INITIAL+$0094
SPR_PLAYER_LEGS_13: equ SPR_INITIAL+$00A0
SPR_PLAYER_LEGS_14: equ SPR_INITIAL+$00A4
SPR_PLAYER_LEGS_15: equ SPR_INITIAL+$00AA
SPR_PLAYER_FOOT_1: equ SPR_INITIAL+$00AD
SPR_PLAYER_FOOT_2: equ SPR_INITIAL+$00B1
SPR_PLAYER_FOOT_3: equ SPR_INITIAL+$00B5
SPR_CRATE: equ SPR_INITIAL+$00B9
SPR_HYDRANT: equ SPR_INITIAL+$00BF
SPR_BUS_STOP_SIGN_TOP: equ SPR_INITIAL+$00C5
SPR_BUS_STOP_SIGN_MIDDLE: equ SPR_INITIAL+$00CD
SPR_BUS_STOP_SIGN_BOTTOM: equ SPR_INITIAL+$00D1
SPR_OVERHEAD_SIGN_TOP_LEFT: equ SPR_INITIAL+$00D5
SPR_OVERHEAD_SIGN_TOP_RIGHT: equ SPR_INITIAL+$00DD
SPR_OVERHEAD_SIGN_MIDDLE: equ SPR_INITIAL+$00E5
SPR_OVERHEAD_SIGN_BOTTOM: equ SPR_INITIAL+$00E8
SPR_LIGHT_POLE_TOP: equ SPR_INITIAL+$00EB
SPR_LIGHT_POLE_MIDDLE: equ SPR_INITIAL+$00F1
SPR_LIGHT_POLE_BOTTOM: equ SPR_INITIAL+$00F5
SPR_COIN_1: equ SPR_INITIAL+$00F8
SPR_COIN_2: equ SPR_INITIAL+$00F9
SPR_COIN_3: equ SPR_INITIAL+$00FA
SPR_SPARK_SILVER_1: equ SPR_INITIAL+$00FB
SPR_SPARK_SILVER_2: equ SPR_INITIAL+$00FC
SPR_SPARK_SILVER_3: equ SPR_INITIAL+$00FD
SPR_SPARK_GOLD_1: equ SPR_INITIAL+$00FE
SPR_SPARK_GOLD_2: equ SPR_INITIAL+$00FF
SPR_SPARK_GOLD_3: equ SPR_INITIAL+$0100
SPR_BANANA_PEEL: equ SPR_INITIAL+$0101
SPR_SPRING_1: equ SPR_INITIAL+$0102
SPR_SPRING_2: equ SPR_INITIAL+$0104
SPR_SPRING_3: equ SPR_INITIAL+$0106
SPR_SPRING_4: equ SPR_INITIAL+$0108
SPR_GUSH_TOP_1: equ SPR_INITIAL+$010A
SPR_GUSH_TOP_2: equ SPR_INITIAL+$010C
SPR_GUSH_TOP_3: equ SPR_INITIAL+$010E
SPR_GUSH_MIDDLE_1: equ SPR_INITIAL+$0110
SPR_GUSH_MIDDLE_2: equ SPR_INITIAL+$0118
SPR_GUSH_MIDDLE_3: equ SPR_INITIAL+$0120
SPR_GUSH_HOLE: equ SPR_INITIAL+$0128
SPR_GUSH_CRACK: equ SPR_INITIAL+$0130
SPR_CRACK_PARTICLE_1: equ SPR_INITIAL+$0132
SPR_CRACK_PARTICLE_2: equ SPR_INITIAL+$0133
SPR_VERTICAL_ROPE_TOP: equ SPR_INITIAL+$0134
SPR_VERTICAL_ROPE_BOTTOM: equ SPR_INITIAL+$0138
SPR_PUSH_ARROW_1: equ SPR_INITIAL+$013A
SPR_PUSH_ARROW_2: equ SPR_INITIAL+$0146
SPR_HEN_UPPER_BODY: equ SPR_INITIAL+$0149
SPR_HEN_LEGS_1: equ SPR_INITIAL+$0151
SPR_HEN_LEGS_2: equ SPR_INITIAL+$0153
SPR_HEN_LEGS_3: equ SPR_INITIAL+$0155
SPR_BUS_DOOR_1_TOP: equ SPR_INITIAL+$0157
SPR_BUS_DOOR_1_MIDDLE: equ SPR_INITIAL+$0163
SPR_BUS_DOOR_2_TOP: equ SPR_INITIAL+$016C
SPR_BUS_DOOR_2_MIDDLE: equ SPR_INITIAL+$0174
SPR_BUS_DOOR_3_TOP: equ SPR_INITIAL+$017A
SPR_BUS_DOOR_3_MIDDLE: equ SPR_INITIAL+$017E
SPR_BUS_DOOR_4_TOP: equ SPR_INITIAL+$0181
SPR_BUS_DOOR_4_MIDDLE: equ SPR_INITIAL+$0185
SPR_BUS_WHEEL_1: equ SPR_INITIAL+$0188
SPR_BUS_WHEEL_2: equ SPR_INITIAL+$0194
SPR_BUS_WHEEL_3: equ SPR_INITIAL+$01A0
SPR_BUS_ROUTE_SIGN_GOAL: equ SPR_INITIAL+$01AC
SPR_BUS_ROUTE_SIGN_2: equ SPR_INITIAL+$01B0
SPR_BUS_ROUTE_SIGN_3: equ SPR_INITIAL+$01B4
SPR_BUS_ROUTE_SIGN_4: equ SPR_INITIAL+$01B8
SPR_BUS_ROUTE_SIGN_5: equ SPR_INITIAL+$01BC
SPR_BUS_CHARACTER_1_HEAD: equ SPR_INITIAL+$01C0
SPR_BUS_CHARACTER_1_TORSO: equ SPR_INITIAL+$01C2
SPR_BUS_CHARACTER_1_LEGS: equ SPR_INITIAL+$01C5
SPR_BUS_CHARACTER_2_HEAD: equ SPR_INITIAL+$01C8
SPR_BUS_CHARACTER_2_TORSO: equ SPR_INITIAL+$01CA
SPR_BUS_CHARACTER_2_LEGS: equ SPR_INITIAL+$01CC
SPR_BUS_CHARACTER_3_HEAD: equ SPR_INITIAL+$01CF
SPR_BUS_CHARACTER_3_TORSO: equ SPR_INITIAL+$01D1
SPR_BUS_CHARACTER_3_LEGS: equ SPR_INITIAL+$01D4
SPR_CAR_TOP_1: equ SPR_INITIAL+$01D7
SPR_CAR_TOP_2: equ SPR_INITIAL+$01DF
SPR_CAR_MIDDLE_1: equ SPR_INITIAL+$01E7
SPR_CAR_MIDDLE_2: equ SPR_INITIAL+$01F7
SPR_CAR_MIDDLE_3: equ SPR_INITIAL+$0207
SPR_CAR_MIDDLE_4: equ SPR_INITIAL+$0217
SPR_CAR_WHEEL_BOTTOM: equ SPR_INITIAL+$0227
SPR_CAR_WHEEL_MIDDLE_1: equ SPR_INITIAL+$022A
SPR_CAR_WHEEL_MIDDLE_2: equ SPR_INITIAL+$022C
SPR_DEEP_HOLE_LEFT_FG: equ SPR_INITIAL+$022E
SPR_PASSAGEWAY_LEFT_FG: equ SPR_INITIAL+$0234
SPR_PASSAGEWAY_RIGHT_FG: equ SPR_INITIAL+$0240
SPR_PASSAGEWAY_RIGHT_CLOSED: equ SPR_INITIAL+$0246
SPR_HORIZONTAL_ROPE_EDGE_LEFT: equ SPR_INITIAL+$024C
SPR_HORIZONTAL_ROPE_EDGE_RIGHT: equ SPR_INITIAL+$0250
SPR_PLAYER_RUN_UPPER_BODY: equ SPR_INITIAL+$0254
SPR_PLAYER_RUN_ARM: equ SPR_INITIAL+$025A
SPR_PLAYER_RUN_LEGS_1: equ SPR_INITIAL+$025E
SPR_PLAYER_RUN_LEGS_2: equ SPR_INITIAL+$026E
SPR_PLAYER_RUN_LEGS_3: equ SPR_INITIAL+$027A
SPR_PLAYER_RUN_LEGS_4: equ SPR_INITIAL+$028A
SPR_PLAYER_RUN_FOOT_1: equ SPR_INITIAL+$0296
SPR_PLAYER_RUN_FOOT_2: equ SPR_INITIAL+$0298
SPR_PLAYER_HEAD_FRONT: equ SPR_INITIAL+$029A
SPR_PLAYER_CLEANING_1: equ SPR_INITIAL+$029B
SPR_PLAYER_CLEANING_2: equ SPR_INITIAL+$02A1
SPR_PLAYER_CLEANING_3: equ SPR_INITIAL+$02A7
SPR_PLAYER_CLEANING_4: equ SPR_INITIAL+$02AD
SPR_PLAYER_CLEANING_LEGS: equ SPR_INITIAL+$02B3
SPR_PLAYER_CLEANING_HAND: equ SPR_INITIAL+$02BB
SPR_BEARDED_MAN_HEAD: equ SPR_INITIAL+$02BC
SPR_BEARDED_MAN_TORSO_1: equ SPR_INITIAL+$02BE
SPR_BEARDED_MAN_TORSO_2: equ SPR_INITIAL+$02C2
SPR_BEARDED_MAN_TORSO_3: equ SPR_INITIAL+$02CA
SPR_BEARDED_MAN_TORSO_4: equ SPR_INITIAL+$02D2
SPR_BIRD_1: equ SPR_INITIAL+$02DA
SPR_BIRD_2: equ SPR_INITIAL+$02DC
SPR_BIRD_3: equ SPR_INITIAL+$02DE
SPR_BIRD_DUNG_1: equ SPR_INITIAL+$02E0
SPR_BIRD_DUNG_2: equ SPR_INITIAL+$02E1
SPR_BIRD_DUNG_3: equ SPR_INITIAL+$02E2
SPR_FLAGMAN_UPPER_BODY: equ SPR_INITIAL+$02E3
SPR_FLAGMAN_LOWER_BODY: equ SPR_INITIAL+$02EB
SPR_FLAGMAN_ARM_1: equ SPR_INITIAL+$02F3
SPR_FLAGMAN_ARM_2: equ SPR_INITIAL+$02F6
SPR_FLAGMAN_ARM_3: equ SPR_INITIAL+$02FA
SPR_FLAGMAN_FLAG_1: equ SPR_INITIAL+$02FD
SPR_FLAGMAN_FLAG_2: equ SPR_INITIAL+$0306
SPR_FLAGMAN_FLAG_3: equ SPR_INITIAL+$0312
SPR_ENDING_MEDAL_CONTAINER: equ SPR_INITIAL+$031B
SPR_ENDING_MEDAL_1: equ SPR_INITIAL+$0327
SPR_ENDING_MEDAL_2: equ SPR_INITIAL+$032B
SPR_ENDING_MEDAL_3: equ SPR_INITIAL+$032F

; Screen wipe commands
WIPECMD_NONE:  equ 0
WIPECMD_IN:    equ 1
WIPECMD_OUT:   equ 2
WIPECMD_CLEAR: equ 3

; Sound effects
SFX_COIN: equ $00
SFX_CRATE: equ $01
SFX_FALL: equ $02
SFX_HIT: equ $03
SFX_HOLE: equ $04
SFX_RESPAWN: equ $05
SFX_SCORE: equ $06
SFX_SELECT: equ $07
SFX_SLIP: equ $08
SFX_SPRING: equ $09
SFX_TIME: equ $0A

; Special constant meaning that something does not exist or is unset or inactive
NONE: equ -1

; Screen types
SCR_NONE:          equ 0
SCR_MENU:          equ 1
SCR_FINALSCORE:    equ 2
SCR_PLAY:          equ 3

; Difficulties
DIFFICULTY_NORMAL: equ 0
DIFFICULTY_HARD:   equ 1
DIFFICULTY_SUPER:  equ 2
DIFFICULTY_MAX:    equ DIFFICULTY_SUPER

; Delayed action types
DELACT_NONE:            equ 0
DELACT_START_PLAY:      equ 1
DELACT_NEXT_DIFFICULTY: equ 2
DELACT_TITLE:           equ 3

; Menu types
MENU_MAIN:         equ 0
MENU_PAUSE:        equ 1
MENU_DIFFICULTY:   equ 2
MENU_LEVEL5:       equ 3
MENU_LEVEL3:       equ 4
MENU_JUKEBOX:      equ 5
MENU_RESTART:      equ 6
MENU_TRY_AGAIN:    equ 7
MENU_QUIT:         equ 8
MENU_ABOUT:        equ 9
MENU_CREDITS:      equ 10

; Menu action types
MENUACT_NONE:      equ 0
MENUACT_TITLE:     equ 1
MENUACT_PLAY:      equ 2
MENUACT_RESUME:    equ 3
MENUACT_TRY_AGAIN: equ 4

; Gameplay input actions
PLAY_INPUT_LEFT:   equ 0
PLAY_INPUT_RIGHT:  equ 1
PLAY_INPUT_JUMP:   equ 2

; Animations
ANIM_SIZE_BYTES:       equ 8
ANIM_PLAYER:           equ (0*ANIM_SIZE_BYTES)
ANIM_COINS:            equ (1*ANIM_SIZE_BYTES)
ANIM_GUSHES:           equ (2*ANIM_SIZE_BYTES)
ANIM_HIT_SPRING:       equ (3*ANIM_SIZE_BYTES)
ANIM_CRACK_PARTICLES:  equ (4*ANIM_SIZE_BYTES)
ANIM_BUS_WHEELS:       equ (5*ANIM_SIZE_BYTES)
ANIM_BUS_DOOR_REAR:    equ (6*ANIM_SIZE_BYTES)
ANIM_BUS_DOOR_FRONT:   equ (7*ANIM_SIZE_BYTES)
ANIM_CAR_WHEELS:       equ (8*ANIM_SIZE_BYTES)
ANIM_HEN:              equ (9*ANIM_SIZE_BYTES)
ANIM_COIN_SPARK_1:     equ (10*ANIM_SIZE_BYTES)
ANIM_COIN_SPARK_2:     equ (11*ANIM_SIZE_BYTES)
ANIM_COIN_SPARK_3:     equ (12*ANIM_SIZE_BYTES)
ANIM_COIN_SPARK_4:     equ (13*ANIM_SIZE_BYTES)
ANIM_COIN_SPARK_5:     equ (14*ANIM_SIZE_BYTES)
ANIM_COIN_SPARK_6:     equ (15*ANIM_SIZE_BYTES)
ANIM_COIN_SPARK_7:     equ (16*ANIM_SIZE_BYTES)
ANIM_COIN_SPARK_8:     equ (17*ANIM_SIZE_BYTES)
ANIM_COIN_SPARK_9:     equ (18*ANIM_SIZE_BYTES)
ANIM_COIN_SPARK_10:    equ (19*ANIM_SIZE_BYTES)
ANIM_COIN_SPARK_11:    equ (20*ANIM_SIZE_BYTES)
ANIM_COIN_SPARK_12:    equ (21*ANIM_SIZE_BYTES)
ANIM_COIN_SPARK_13:    equ (22*ANIM_SIZE_BYTES)
ANIM_COIN_SPARK_14:    equ (23*ANIM_SIZE_BYTES)
ANIM_COIN_SPARK_15:    equ (24*ANIM_SIZE_BYTES)
ANIM_COIN_SPARK_16:    equ (25*ANIM_SIZE_BYTES)
ANIM_CUTSCENE_OBJ_1:   equ (26*ANIM_SIZE_BYTES)
ANIM_CUTSCENE_OBJ_2:   equ (27*ANIM_SIZE_BYTES)
NUM_ANIMS:             equ 28

; Player character's states
PLAYER_STATE_NORMAL: equ 0
PLAYER_STATE_SLIP: equ 1
PLAYER_STATE_GETUP: equ 2
PLAYER_STATE_THROWBACK: equ 3
PLAYER_STATE_GRABROPE: equ 4
PLAYER_STATE_FLICKER: equ 5
PLAYER_STATE_INACTIVE: equ 6

; Player character's animation types
PLAYER_ANIM_STAND:     equ 0
PLAYER_ANIM_WALK:      equ 1
PLAYER_ANIM_WALKBACK:  equ 2
PLAYER_ANIM_JUMP:      equ 3
PLAYER_ANIM_SLIP:      equ 4
PLAYER_ANIM_SLIPREV:   equ 5 ; Reverse slip
PLAYER_ANIM_THROWBACK: equ 6
PLAYER_ANIM_GRABROPE:  equ 7

; Player character's bounding box and height
PLAYER_BOX_OFFSET_X: equ 8
PLAYER_BOX_WIDTH: equ 12
PLAYER_HEIGHT_NORMAL: equ 60
PLAYER_HEIGHT_SLIP: equ 38

; Solid types
SOL_FULL: equ 0
SOL_VERTICAL: equ 1
SOL_SLOPE_UP: equ 2
SOL_SLOPE_DOWN: equ 3
SOL_KEEP_ON_TOP: equ 4
SOL_PASSAGEWAY_ENTRY: equ 5
SOL_PASSAGEWAY_EXIT: equ 6

FLOOR_Y: equ 264

; Object types
OBJ_NULL: equ 0
OBJ_BANANA_PEEL: equ 1
OBJ_GUSH: equ 2
OBJ_GUSH_CRACK: equ 3
OBJ_PUSH_CRATE: equ 4
OBJ_PUSH_CRATE_WITH_ARROW: equ 5
OBJ_ROPE: equ 6
OBJ_SPRING: equ 7

; Vehicle types
VEH_NONE: equ 0
VEH_PARKED_CAR_BLUE: equ 1
VEH_PARKED_CAR_SILVER: equ 2 
VEH_PARKED_CAR_YELLOW: equ 3
VEH_PARKED_TRUCK: equ 4
VEH_BUS: equ 5
VEH_ENDING_CAR_BLUE: equ 6
VEH_ENDING_CAR_SILVER: equ 7
VEH_ENDING_CAR_YELLOW: equ 8

; Maximum numbers
MAX_OBJS: equ 160
MAX_PASSAGEWAYS: equ 4
MAX_CRACK_PARTICLES: equ 16
MAX_COIN_SPARKS: equ 16
MAX_GUSHES: equ 32
MAX_MOVING_PEELS: equ 2
MAX_PUSHABLE_CRATES: equ 4

; Objects with a fixed Y position
BUS_Y: equ 128
BUS_STOP_SIGN_Y: equ 176
POLE_Y: equ 120
HYDRANT_Y: equ 240
ROPE_Y: equ 144
PASSING_CAR_Y: equ 184
HEN_Y: equ 224

; Cutscene object types
COBJ_NONE: equ 0
COBJ_PLAYER_STAND: equ 1
COBJ_PLAYER_WALK: equ 2
COBJ_PLAYER_RUN: equ 3
COBJ_PLAYER_CLEAN_DUNG: equ 4
COBJ_BEARDED_MAN_STAND: equ 5
COBJ_BEARDED_MAN_WALK: equ 6
COBJ_BEARDED_MAN_JUMP: equ 7
COBJ_BIRD: equ 8
COBJ_DUNG: equ 9
COBJ_FLAGMAN: equ 10

; Sequence types
SEQ_NORMAL_PLAY_START: equ 0
SEQ_NORMAL_PLAY: equ 1
SEQ_INITIAL: equ 10
SEQ_BUS_LEAVING: equ 20
SEQ_TIMEUP_BUS_NEAR: equ 30
SEQ_TIMEUP_BUS_FAR: equ 40
SEQ_GOAL_REACHED: equ 50
SEQ_GOAL_REACHED_SCENE1: equ 60
SEQ_GOAL_REACHED_SCENE2: equ 70
SEQ_GOAL_REACHED_SCENE3: equ 80
SEQ_GOAL_REACHED_SCENE4: equ 90
SEQ_GOAL_REACHED_SCENE5: equ 100
SEQ_ENDING: equ 110
SEQ_FINISHED: equ 255

